apiVersion: v1
kind: Service
metadata:
  name: fake-rest-service
  namespace: kubernetes-dashboard
  labels:
    app: fake-rest-service
spec:
  selector:
    app: fake-rest-service
  type: ClusterIP  # default; internal-only access
  ports:
    - port: 8082         # Service port (used by Gateway or other clients)
      targetPort: 8082   # Port exposed by the pod container