spring:
  profiles:
    active: dev
  application:
    name: fake-rest-service
  main:
    banner-mode: off

server:
  port: 8082

user:
  username: ${APP_USERNAME:hari}
  password: ${APP_PASSWORD:June@123}

sleep:
  time: ${SLEEP_TIME:0}

fake:
  rest:
    jsonPlaceHolder: ${JSON_PLACEHOLDER_URL:https://jsonplaceholder.typicode.com}
    products: ${PRODUCTS_URL:https://fakestoreapi.com}
    carts: ${CARTS_URL:https://dummyjson.com}
    fakeRestApi: ${FAKEREST_URL:https://fakerestapi.azurewebsites.net}


  #"https://fakestoreapi.com/products",
  #"https://dummyjson.com/carts",
  #"https://fakerestapi.azurewebsites.net/api/v1/Books",
  #"https://fakerestapi.azurewebsites.net/api/v1/Authors",
  #"https://jsonplaceholder.typicode.com/posts",
  #"https://jsonplaceholder.typicode.com/comments",
  #"https://jsonplaceholder.typicode.com/todos",
  #"https://jsonplaceholder.typicode.com/photos"